In [ ]:
# Install ipython-sql via pip
!pip install duckdb numpy pandas

In [12]:
import duckdb

con = duckdb.connect(database=':memory:')

query = """WITH SplitCTE AS (
    SELECT
        *,
        STRING_SPLIT(tx, ' ') AS tx_parts,
        STRING_SPLIT(rx, ' ') AS rx_parts
    FROM read_ndjson_auto('./data/**/*.ndjson')
    WHERE tx LIKE '00 __ 00 %'
    AND rx NOT LIKE '00 __ 00 %'
    AND rx NOT LIKE '00 __ 02 __ 01 %'
)
SELECT src, dev, tx, rx, tx_parts, rx_parts FROM SplitCTE;"""

# Execute SQL
con.execute(query)

# Optionally fetch results from the last query
result = con.fetchdf()
result

,src,dev,tx,rx,tx_parts,rx_parts
0,mvg,BT-E6000,00 1A 00 A6 67,00 9A 07 A6 A1 17 60 56 52 4B F2 9F,"[00, 1A, 00, A6, 67]","[00, 9A, 07, A6, A1, 17, 60, 56, 52, 4B, F2, 9F]"
1,mvg,BT-E6000,00 92 00 AA 25,00 92 03 AA 90 01 5E B6,"[00, 92, 00, AA, 25]","[00, 92, 03, AA, 90, 01, 5E, B6]"
2,mvg,BT-E6000,00 97 00 12 5B,00 97 0A 12 25 00 E1 00 00 90 10 0F 00 34 14,"[00, 97, 00, 12, 5B]","[00, 97, 0A, 12, 25, 00, E1, 00, 00, 90, 10, 0..."
3,mvg,BT-E6000,00 A9 00 A0 77,00 A9 2B A0 00 00 00 00 1F 00 00 00 34 00 34 0...,"[00, A9, 00, A0, 77]","[00, A9, 2B, A0, 00, 00, 00, 00, 1F, 00, 00, 0..."
4,mvg,BT-E6000,00 B7 00 21 78,00 B7 03 21 25 FF F6 8F,"[00, B7, 00, 21, 78]","[00, B7, 03, 21, 25, FF, F6, 8F]"
5,mvg,BT-E6000,00 B9 00 31 E2,00 B9 12 31 25 9F 01 A9 01 01 00 05 00 28 00 6...,"[00, B9, 00, 31, E2]","[00, B9, 12, 31, 25, 9F, 01, A9, 01, 01, 00, 0..."

It seems like this exposes some possible commands, I would like to run a test where the first CRC byte increments by one.  
I suspect it will expose all commands the device knows.  
  
CRC byte was a bit unpredictable, so I created short messages for each possible command/type byte.

In [ ]:
# Possible Commands
import duckdb

con = duckdb.connect(database=':memory:')

query = """WITH SplitCTE AS (
    SELECT
        *,
        STRING_SPLIT(tx, ' ') AS tx_parts,
        STRING_SPLIT(rx, ' ') AS rx_parts
    FROM read_ndjson_auto('./data/**/*.ndjson')
    WHERE intent = 'Command sniffing'
    AND tx LIKE '00 __ 02 %'
    AND (rx NOT LIKE '00 __ 02 __ 01 %' or rx = '')
    
)
SELECT dev, tx, rx, notes FROM SplitCTE;"""

# Execute SQL
con.execute(query)

# Optionally fetch results from the last query
result = con.fetchdf()
result

,dev,tx,rx,notes
0,BT-E6000,00 40 02 10 00 40 CA,00 C0 16 10 25 00 00 02 00 E5 00 66 00 08 00 1...,OK
1,BT-E6000,00 41 02 11 00 23 CF,00 C1 09 11 25 47 00 0F 03 00 00 64 A0 B9,OK
2,BT-E6000,00 42 02 12 00 86 C0,00 C2 0A 12 25 00 E1 00 00 90 10 0F 00 AF D6,OK
3,BT-E6000,00 43 02 13 00 E5 C5,00 C3 20 13 25 00 01 01 00 04 0A 01 02 52 0A 0...,OK
4,BT-E6000,00 40 02 20 00 E2 7C,00 C0 03 20 25 00 7D FF,OK
5,BT-E6000,00 41 02 21 00 81 79,00 C1 03 21 25 FF 9D A1,OK
6,BT-E6000,00 40 02 30 00 73 E9,00 C0 02 30 12 8E F7,OK
7,BT-E6000,00 41 02 31 00 10 EC,,TIMEOUT
8,BT-E6000,00 42 02 32 00 B5 E3,00 C2 02 32 12 48 FD,OK
9,BT-E6000,00 40 02 A0 00 2E F0,00 C0 2B A0 00 00 00 00 21 00 0E 00 33 00 32 0...,OK
10,BT-E6000,00 41 02 A1 00 4D F5,,TIMEOUT
11,BT-E6000,00 42 02 A2 00 E8 FA,,TIMEOUT
12,BT-E6000,00 43 02 A3 00 8B FF,,TIMEOUT
13,BT-E6000,00 40 02 A4 00 4E 97,,TIMEOUT
14,BT-E6000,00 41 02 A5 00 2D 92,,TIMEOUT
15,BT-E6000,00 42 02 A6 00 88 9D,00 C2 07 A6 A1 17 60 56 52 4B CF F9,OK
16,BT-E6000,00 43 02 A7 00 EB 98,00 C3 07 A7 CC 00 F3 55 52 4B 73 39,OK
17,BT-E6000,00 42 02 AA 00 28 34,00 C2 03 AA 90 01 3C C3,OK
18,BT-E6000,00 43 02 AB 00 4B 31,00 C3 03 AB 06 01 29 DF,OK
19,BT-E6000,00 40 02 AC 00 8E 59,,TIMEOUT
20,BT-E6000,00 41 02 AD 00 ED 5C,,TIMEOUT
21,BT-E6000,00 42 02 AE 00 48 53,,TIMEOUT
22,BT-E6000,00 43 02 AF 00 2B 56,,TIMEOUT
23,BT-E6000,00 40 02 B0 00 BF 65,,TIMEOUT
24,BT-E6000,00 41 02 B1 00 DC 60,,TIMEOUT
25,BT-E6000,00 42 02 B2 00 79 6F,,TIMEOUT
26,BT-E6000,00 43 02 B3 00 1A 6A,,TIMEOUT
27,BT-E6000,00 40 02 B4 00 DF 02,,TIMEOUT
28,BT-E6000,00 41 02 B5 00 BC 07,,TIMEOUT
29,BT-E6000,00 42 02 B6 00 19 08,,TIMEOUT
30,BT-E6000,00 43 02 B7 00 7A 0D,,TIMEOUT
31,BT-E6000,00 40 02 B8 00 7F AB,,TIMEOUT
32,BT-E6000,00 42 02 BA 00 B9 A1,,TIMEOUT
33,BT-E6000,00 43 02 BB 00 DA A4,00 C3 04 BB 00 00 00 18 70,OK
34,BT-E6000,00 40 02 BC 00 1F CC,,TIMEOUT
35,BT-E6000,00 41 02 BD 00 7C C9,,TIMEOUT
36,BT-E6000,00 42 02 BE 00 D9 C6,,TIMEOUT
37,BT-E6000,00 43 02 BF 00 BA C3,,TIMEOUT
38,BT-E6000,00 43 02 CB 00 1E 54,00 C3 03 CB 00 00 3D 9F,OK
39,BT-E6000,00 40 02 CC 00 DB 3C,,TIMEOUT
40,BT-E6000,00 41 02 CD 00 B8 39,,TIMEOUT
41,BT-E6000,00 42 02 CE 00 1D 36,,TIMEOUT
42,BT-E6000,00 43 02 CF 00 7E 33,,TIMEOUT

Querying the data I noticed that for sender ID 0xB9 command 0x31 does return data.

In [11]:
import duckdb

con = duckdb.connect(database=':memory:')

query = """WITH SplitCTE AS (
    SELECT
        *,
        STRING_SPLIT(tx, ' ') AS tx_parts,
        STRING_SPLIT(rx, ' ') AS rx_parts
    FROM read_ndjson_auto('./data/**/*.ndjson')
    WHERE intent LIKE 'Command sniffing%'
    AND tx LIKE '00 B9 01 %'
    AND (rx NOT LIKE '00 __ 02 __ 01 %' or rx = '')
    
)
SELECT dev, tx, rx, notes FROM SplitCTE;"""

# Execute SQL
con.execute(query)

# Optionally fetch results from the last query
result = con.fetchdf()
result

,dev,tx,rx,notes
0,BT-E6000,00 B9 01 10 C9 D9,00 B9 01 10 C9 D9,OK
1,BT-E6000,00 B9 01 11 40 C8,00 B9 09 11 25 47 00 0F 03 00 00 64 C0 5B,OK
2,BT-E6000,00 B9 01 12 DB FA,00 B9 0A 12 25 00 E1 00 00 90 10 0F 00 A5 32,OK
3,BT-E6000,00 B9 01 13 52 EB,00 B9 02 13 25 CF 18,OK
4,BT-E6000,00 B9 01 20 4A E8,00 B9 03 20 25 00 EA BB,OK
5,BT-E6000,00 B9 01 21 C3 F9,00 B9 03 21 25 FF 4E EE,OK
6,BT-E6000,00 B9 01 30 CB F8,00 B9 02 30 12 A8 54,OK
7,BT-E6000,00 B9 01 31 42 E9,00 B9 12 31 25 9F 01 A9 01 01 00 05 00 28 00 6...,OK
8,BT-E6000,00 B9 01 32 D9 DB,00 B9 02 32 12 18 67,OK
9,BT-E6000,00 B9 01 A0 42 6C,00 B9 2B A0 00 00 00 00 21 00 0B 00 34 00 34 0...,OK
10,BT-E6000,00 B9 01 A1 CB 7D,,TIMEOUT
11,BT-E6000,00 B9 01 A2 50 4F,,TIMEOUT
12,BT-E6000,00 B9 01 A3 D9 5E,,TIMEOUT
13,BT-E6000,00 B9 01 A4 66 2A,,TIMEOUT
14,BT-E6000,00 B9 01 A5 EF 3B,,TIMEOUT
15,BT-E6000,00 B9 01 A6 74 09,00 B9 07 A6 A1 17 60 56 52 4B CC BE,OK
16,BT-E6000,00 B9 01 A7 FD 18,00 B9 07 A7 CC 00 F3 55 52 4B 8D 33,OK
17,BT-E6000,00 B9 01 AA 18 C3,00 B9 03 AA 90 01 23 91,OK
18,BT-E6000,00 B9 01 AB 91 D2,00 B9 03 AB 06 01 72 86,OK
19,BT-E6000,00 B9 01 AC 2E A6,,TIMEOUT
20,BT-E6000,00 B9 01 AD A7 B7,,TIMEOUT
21,BT-E6000,00 B9 01 AE 3C 85,,TIMEOUT
22,BT-E6000,00 B9 01 AF B5 94,,TIMEOUT
23,BT-E6000,00 B9 01 B0 C3 7C,,TIMEOUT
24,BT-E6000,00 B9 01 B1 4A 6D,,TIMEOUT
25,BT-E6000,00 B9 01 B2 D1 5F,,TIMEOUT
26,BT-E6000,00 B9 01 B3 58 4E,,TIMEOUT
27,BT-E6000,00 B9 01 B4 E7 3A,,TIMEOUT
28,BT-E6000,00 B9 01 B5 6E 2B,,TIMEOUT
29,BT-E6000,00 B9 01 B6 F5 19,,TIMEOUT
30,BT-E6000,00 B9 01 B7 7C 08,,TIMEOUT
31,BT-E6000,00 B9 01 B8 8B F0,,TIMEOUT
32,BT-E6000,00 B9 01 BA 99 D3,,TIMEOUT
33,BT-E6000,00 B9 01 BB 10 C2,00 B9 04 BB 00 00 00 17 9C,OK
34,BT-E6000,00 B9 01 BC AF B6,,TIMEOUT
35,BT-E6000,00 B9 01 BD 26 A7,,TIMEOUT
36,BT-E6000,00 B9 01 BE BD 95,,TIMEOUT
37,BT-E6000,00 B9 01 BF 34 84,,TIMEOUT
38,BT-E6000,00 B9 01 CB 97 B1,00 B9 03 CB 00 00 66 C6,OK
39,BT-E6000,00 B9 01 CC 28 C5,,TIMEOUT
40,BT-E6000,00 B9 01 CD A1 D4,,TIMEOUT
41,BT-E6000,00 B9 01 CE 3A E6,,TIMEOUT
42,BT-E6000,00 B9 01 CF B3 F7,,TIMEOUT

0xB9 sender does return for 0x31 type, but no other types suddenly return.

In [5]:
# Unknown command/type reply?
import duckdb

con = duckdb.connect(database=':memory:')

query = """WITH SplitCTE AS (
    SELECT
        *,
        STRING_SPLIT(tx, ' ') AS tx_parts,
        STRING_SPLIT(rx, ' ') AS rx_parts
    FROM read_ndjson_auto('./data/**/*.ndjson')
    WHERE intent = 'Command sniffing'
    AND NOT (tx LIKE '00 __ 02 %'
    AND (rx NOT LIKE '00 __ 02 __ 01 %' or rx = ''))
    
)
SELECT dev, tx, rx, notes FROM SplitCTE;"""

# Execute SQL
con.execute(query)

# Optionally fetch results from the last query
result = con.fetchdf()
result

          dev                             tx                    rx notes
0    BT-E6000  00 40 05 00 00 00 00 00 F1 5F  00 C0 02 00 01 36 63    OK
1    BT-E6000           00 40 02 00 00 D1 5F  00 C0 02 00 01 36 63    OK
2    BT-E6000           00 41 02 01 00 B2 5A  00 C1 02 01 01 55 66    OK
3    BT-E6000           00 42 02 02 00 17 55  00 C2 02 02 01 F0 69    OK
4    BT-E6000           00 43 02 03 00 74 50  00 C3 02 03 01 93 6C    OK
..        ...                            ...                   ...   ...
294  BT-E6000  00 40 05 50 00 00 00 00 93 2A  00 C0 02 50 01 C1 B0    OK
295  BT-E6000  00 41 05 51 00 00 00 00 02 BE  00 C1 02 51 01 A2 B5    OK
296  BT-E6000  00 42 05 52 00 00 00 00 A0 0B  00 C2 02 52 01 07 BA    OK
297  BT-E6000  00 43 05 53 00 00 00 00 31 9F  00 C3 02 53 01 64 BF    OK
298  BT-E6000  00 40 05 54 00 00 00 00 83 07  00 C0 02 54 01 A1 D7    OK

[299 rows x 4 columns]